import Location from "./location.png"

export const data = [
    {
        id: 1,
        city:"تهران",
        tel:"۱۶۳۰",
        address:"تهران، سعادت‌آباد، بالاتر از میدان کاج، بلوار بهزاد، نبش کوچه باغستان یکم، پلاک ۲.",
        code:"۱۹۹۸۶۳۵۸۲۰",
        selected: "selected",
        location:"https://www.google.com/maps/place/Tapsi+Co./@35.788041,51.375486,15z/data=!4m5!3m4!1s0x0:0xe4116f5517d2ab14!8m2!3d35.7880518!4d51.3754838?hl=en",
        img: Location,
    },
    {
        id: 2,
        city:"کرج",
        tel:"",
        address:"کرج، ۴۵ متری گلشهر، خیابان درختی، بین کوچه اول و دوم، مرکز خرید درختی، طبقه پنجم، واحد ۳",
        code:"۳۱۳۷۷۳۳۸۰۳",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 2,
        city:"مشهد",
        tel:"۰۵۱۳۷۰۵۴۰۱۳",
        address:"بلوار جانباز، جانباز ۵/۱، مجتمع مروارید، طبقه ۱۲، واحد ۱",
        code:"۹۱۹۷۶۱۳۵۲۵",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 3,
        city:"اصفهان",
        tel:"۰۳۱۳۲۶۸۷۴۰۸",
        address:"اصفهان، خیابان بزرگمهر، بعد از خیابان رکن‌الدوله غربی، روبروی پارکینگ طبقاتی، مجتمع آمتیس، طبقه ۵، واحد ۵۰۵",
        code:"۸۱۵۸۸۶۷۷۹۱",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 4,
        city:"شیراز",
        tel:"",
        address:"شیراز، معالي آباد ، كوچه ۳۱ ، درب دوم سمت راست، ساختمان اوتانا ۲ ، طبقه اول ، واحد ۱۰۴",
        code:"۷۱۸۷۶۳۳۱۴۳",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 5,
        city:"ارومیه",
        tel:"۰۴۴۳۳۴۶۲۶۱۵",
        address:"چهارراه مخابرات، کوچه مخابرات، برج جواهر، طبقه ۲، واحد ۳",
        code:"57156114113",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 7,
        city:"لاهیجان",
        tel:"",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 8,
        city:"رشت",
        tel:"۰۱۳۳۲۱۳‍۱۹۶۰",
        address:"رشت، گلسار، میدان صابرین، برج ایرانیان، طبقه ۱۰، واحد ۲",
        code:"۴۱‍۶۴۹۸۴۴۹۵",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 9,
        city:"انزلی",
        tel:"",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 10,
        city:"تبریز",
        tel:"۰۴۱۳۳۳۰۷۸۰۰",
        address:"خیابان دروازه تهران، سه راهی ولیعصر، برج سینا، طبقه ۷، واحد ۱",
        code:"۵۱۵۷۹۸۳۵۱۳",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 11,
        city:"ساری",
        tel:"۰۱۱۳۳۲۱۰۴۷۰",
        address:"بلوار فرح آباد، نبش فرح آباد هشتم، مجتمع باغبان، طبقه ۵، واحد ۵۱",
        code:"۴۸۱۶۹۷۶۵۳۶",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 12,
        city:"یزد",
        tel:"",
        address:" خیابان شهیدان اشرف، بعد از چهارراه سیتی سنتر، روبروی درب دانشگاه ملاصدرا، ساختمان شمس، طبقه ۲",
        code:"۸۹۱۵۸۵۵۵۵۳",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 13,
        city:"کرمان",
        tel:"۳۴۳۲۴۷۲۴۰۰",
        address:"کرمان، بلوار جمهوری اسلامی، بعد از 20 متری نادر(لاری نجفی)، ساختمان فرد، طبقه ۵ ، واحد ۱۸",
        code:"۷۶۱۹۶۴۷۹۰۷",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 14,
        city:"قم",
        tel:"۰۲۵۳۷۸۳۲۷۸۴",
        address:"میدان معلم، معلم شرقی، ساختمان عمرانیه ، طبقه دوم ، واحد ۲",
        code:"۳۷۱۵۸۳۹۸۶۴",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 15,
        city:"اهواز",
        tel:"۰۶۱-۳۳۳۶۶۵۴۲",
        address:"کیانپارس، خیابان پهلوان شرقی، انتهای کندرو، پل علی بن مهزیار، ساختمان واد، طبقه ۳، واحد ۵",
        code:"۶۱۵۵۶۹۶۷۰۱",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 16,
        city:"بابل",
        tel:"۰۱۱۴۴۴۲۰۱۸۹",
        address:"کمربندی شرقی ، گلستان ۱۲ ، نبش چهارراه دانش ، مجتمع مازند رفاه ، طبقه دوم، واحد ۲۴",
        code:"۴۷۱۴۸۸۶۲۸۹",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 17,
        city:"قائم‌شهر",
        tel:"",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 18,
        city:"آمل",
        tel:"۰۱۱۴۴۲۲۸۱۲۶",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 19,
        city:"کرمانشاه",
        tel:"",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",
    },
    {
        id: 20,
        city:"گرگان",
        tel:"",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",

    },
    {
        id: 21,
        city:"قزوین",
        tel:"",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",

    },
    {
        id: 22,
        city:"اراک",
        tel:"",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",

    },
    {
        id: 23,
        city:"نیشابور",
        tel:"",
        address:"",
        code:"",
        selected: "",
        location:"",
        img:"",

    },
]